### Goal: make a model to predict a person will survive or not.

Import all the libraries

In [2]:
import pandas as pd
import numpy as np

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv('../train.csv')
df.sample(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
596,597,1,2,"Leitch, Miss. Jessie Wills",female,NaN,0,0,248727,33.00,NaN,S
161,162,1,2,"Watt, Mrs. James (Elizabeth ""Bessie"" Inglis Mi...",female,40.0,0,0,C.A. 33595,15.75,NaN,S

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [4]:
# we do not need some solumns

df.drop(columns=['PassengerId', 'Ticket','Name','Cabin'], inplace=True)
df

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

There are two columns `Age` & `Embarked` with missing values. nedd to impute.

In [5]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

Train-Test-Split

In [6]:
x_train,x_test,y_train,y_test = train_test_split(df.drop(columns='Survived'), df['Survived'], test_size=0.2, random_state=42)

x_train.sample()

     Pclass   Sex  Age  SibSp  Parch     Fare Embarked
445       1  male  4.0      0      2  81.8583        S

SimpleImputer on `Age` & `Embarked`

In [7]:
se = SimpleImputer()
se_embarked = SimpleImputer(strategy='most_frequent')

x_train_age = se.fit_transform(x_train[['Age']])
x_train_embarked = se_embarked.fit_transform(x_train[['Embarked']])

x_test_age = se.transform(x_test[['Age']])
x_test_embarked = se_embarked.transform(x_test[['Embarked']])

x_train_age.shape

(712, 1)

One Hot encoding on `Sex` & `Embarked` columns

In [8]:
ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
ohe_embarked = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

x_train_sex = ohe.fit_transform(x_train[['Sex']])
x_train_embarked = ohe_embarked.fit_transform(x_train_embarked)

x_test_sex = ohe.transform(x_test[['Sex']])
x_test_embarked = ohe_embarked.transform(x_test_embarked)

x_train_embarked

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]], shape=(712, 3))

In [9]:
x_train_new = x_train.drop(columns=['Sex', 'Age', 'Embarked'], axis=1)

x_test_new = x_test.drop(columns=['Sex', 'Age', 'Embarked'], axis=1)

x_train_final = np.concatenate((x_train_new, x_train_age,x_train_sex,x_train_embarked),axis=1)
x_test_final = np.concatenate((x_test_new, x_test_age,x_test_sex,x_test_embarked),axis=1)

x_train_final

array([[1., 0., 0., ..., 0., 0., 1.],
       [2., 0., 0., ..., 0., 0., 1.],
       [3., 0., 0., ..., 0., 0., 1.],
       ...,
       [3., 2., 0., ..., 0., 0., 1.],
       [1., 1., 2., ..., 0., 0., 1.],
       [1., 0., 1., ..., 0., 0., 1.]], shape=(712, 10))

In [10]:
clf = DecisionTreeClassifier()

clf.fit(x_train_final,y_train)

DecisionTreeClassifier()

In [11]:
y_pred = clf.predict(x_test_final)

In [12]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_pred)

0.7932960893854749

In [13]:
import os

print(os.listdir('/home/mypc/Desktop/180-Days-of-Code/Day10'))

['useWithoutPiplineModel']

In [14]:
# import pickle

# models = {
#     "clf.pkl": clf,
#     "ohe.pkl": ohe,
#     "ohe_embarked.pkl": ohe_embarked
# }

# for filename, model in models.items():
#     with open(f"useWithoutPiplineModel/{filename}", "wb") as f:
#         pickle.dump(model, f)