# Playlist: 100 Days of ML
1. Working with Json

- downlaod kaggle API key & put it *`~/.kaggle/kaggle.json`*  location to download kaggle dataset with command line.

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle
!chmod 600 ~/.kaggle/kaggle.json

- Listing datset with keyword ***`recipe ingredients`***

In [ ]:
!kaggle datasets list -s "recipe ingredients"

ref                                                             title                                                   size  lastUpdated                 downloadCount  voteCount  usabilityRating
--------------------------------------------------------------  ------------------------------------------------  ----------  --------------------------  -------------  ---------  ---------------
kaggle/recipe-ingredients-dataset                               Recipe Ingredients Dataset                           2335503  2017-01-19 02:55:45.820000          37342        317  0.75
hugodarwood/epirecipes                                          Epicurious - Recipes with Rating and Nutrition      11830041  2017-02-21 09:57:30.380000          26766        284  0.7058824
pes12017000148/food-ingredients-and-recipe-dataset-with-images  Food Ingredients and Recipes Dataset with Images   216485770  2021-02-19 12:05:56.783000          16897        115  1
fasihcs/recipe-ingredients-image-dataset                        Recipe Ingredients Image Dataset                   705542392  2024-05-18 15:09:18.600000            327         28  0.8125
sterby/german-recipes-dataset                                   German Recipes Dataset                               4749666  2019-03-06 16:25:22.603000           5816         78  1
sooryaprakash12/cleaned-indian-recipes-dataset                  Indian Food Recipes Dataset (Cleaned Version)        3378791  2021-03-18 10:34:18.247000           3996         40  0.7941176
prashantsingh001/recipes-dataset-64k-dishes                     Recipes Dataset : 64k Dishes                        41828627  2025-09-27 17:33:09.637000           1961         36  1
canggih/indonesian-food-recipes                                 Indonesian Food Recipes                              3809213  2019-10-17 23:17:12.440000           5832        102  1
campusx/5000-indian-cuisines-datasetwith-images                 5000 Indian Cuisines Dataset(with images)         1184112648  2021-10-30 11:03:48.620000           1681         70  0.9411765
irkaal/foodcom-recipes-and-reviews                              Food.com - Recipes and Reviews                     758217627  2020-12-28 15:56:04.647000          20027        133  1
kanaryayi/recipe-ingredients-and-reviews                        Recipe Ingredients and Reviews                     108317762  2019-02-18 19:14:06.743000           1781         28  0.4117647
prajwaldongre/collection-of-recipes-around-the-world            Collection of Recipes around the world                  9659  2025-04-26 10:08:18.337000           1497         27  1
aadyasingh55/cocktails                                          Cocktails                                              53374  2024-10-22 13:52:07.227000           1294         14  1
thedevastator/better-recipes-for-a-better-life                  Recipes Dataset                                       466413  2022-11-29 17:45:52.943000           6765         36  1
tysonpo/ice-cream-dataset                                       Ice Cream Dataset                                   55330893  2020-10-04 19:09:04.717000           9153         89  0.9411765
uom190346a/tastetrios-exploring-ingredient-combinations         TasteTrios - Exploring Ingredient Combinations          4381  2023-12-12 04:48:25.880000           1216         34  1
michau96/recipes-from-reddit                                    Recipes from Reddit                                  1683657  2022-07-19 15:55:02.483000            618         32  1
wafaaelhusseini/extended-recipes-dataset-64k-dishes             Extended Recipes Dataset: 64K Dishes                82144846  2025-10-20 15:09:59.920000           1010         38  1
pavlosnigur/zelda-botw-food-complete                            Zelda Complete Food and Elixirs Dataset                 3601  2025-12-05 15:49:55.950000            235         24  1
decentsanage/indian-dishes-analysis-dataset                     Indian Dishes Analysis Dataset                           666  2024-08-11 23:28:26.300000            726         24  0.8235294

- Downlaoding a dataset

In [ ]:
!kaggle datasets download -d kaggle/recipe-ingredients-dataset

Dataset URL: https://www.kaggle.com/datasets/kaggle/recipe-ingredients-dataset
License(s): unknown
Downloading recipe-ingredients-dataset.zip to /content
100% 2.23M/2.23M [00:00<00:00, 117MB/s]

- Extracting the dataset from ziofile to normal filetype(JSON)

In [ ]:
import zipfile
!mkdir -p extracted_data
extracted_data = '/content/extracted_data'
with zipfile.ZipFile('/content/recipe-ingredients-dataset.zip', 'r') as f:
  f.extractall(extracted_data)

!ls extracted_data/

test.json  train.json

In [ ]:
import pandas as pd

pd.read_json('/content/extracted_data/test.json')

         id                                        ingredients
0     18009  [baking powder, eggs, all-purpose flour, raisi...
1     28583  [sugar, egg yolks, corn starch, cream of tarta...
2     41580  [sausage links, fennel bulb, fronds, olive oil...
3     29752  [meat cuts, file powder, smoked sausage, okra,...
4     35687  [ground black pepper, salt, sausage casings, l...
...     ...                                                ...
9939  30246  [large egg yolks, fresh lemon juice, sugar, bo...
9940  36028  [hot sauce, butter, sweet potatoes, adobo sauc...
9941  22339  [black pepper, salt, parmigiano reggiano chees...
9942  42525  [cheddar cheese, cayenne, paprika, plum tomato...
9943   1443  [cold water, olive oil, lime wedges, garlic cl...

[9944 rows x 2 columns]

- Reading the dataset using APIs

In [ ]:
pd.read_json('https://restcountries.com/v3.1/all?fields=name,capital,currencies')

,name,currencies,capital
0,"{'common': 'Anguilla', 'official': 'Anguilla',...","{'XCD': {'name': 'Eastern Caribbean dollar', '...",[The Valley]
1,"{'common': 'Guatemala', 'official': 'Republic ...","{'GTQ': {'name': 'Guatemalan quetzal', 'symbol...",[Guatemala City]
2,"{'common': 'Gambia', 'official': 'Republic of ...","{'GMD': {'name': 'dalasi', 'symbol': 'D'}}",[Banjul]
3,"{'common': 'Mexico', 'official': 'United Mexic...","{'MXN': {'name': 'Mexican peso', 'symbol': '$'}}",[Mexico City]
4,"{'common': 'Malawi', 'official': 'Republic of ...","{'MWK': {'name': 'Malawian kwacha', 'symbol': ...",[Lilongwe]
...,...,...,...
245,"{'common': 'Central African Republic', 'offici...","{'XAF': {'name': 'Central African CFA franc', ...",[Bangui]
246,"{'common': 'Sudan', 'official': 'Republic of t...","{'SDG': {'name': 'Sudanese pound', 'symbol': '...",[Khartoum]
247,"{'common': 'Guinea-Bissau', 'official': 'Repub...","{'XOF': {'name': 'West African CFA franc', 'sy...",[Bissau]
248,"{'common': 'Papua New Guinea', 'official': 'In...","{'PGK': {'name': 'Papua New Guinean kina', 'sy...",[Port Moresby]
249,{'common': 'United States Minor Outlying Islan...,"{'USD': {'name': 'United States dollar', 'symb...",[Washington DC]

In [ ]:
pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

2. Working with SQL datasets

<p align="center">
  <picture>
    <source
      srcset="https://github-readme-stats.vercel.app/api?username=pamit7d&show_icons=true&theme=tokyonight"
      media="(prefers-color-scheme: dark)"
    />

    <source
      srcset="https://github-readme-stats.vercel.app/api?username=pamit7d&show_icons=true&theme=default"
      media="(prefers-color-scheme: light), (prefers-color-scheme: no-preference)"
    />

    <img
      height="180em"
      src="https://github-readme-stats.vercel.app/api?username=pamit7d&show_icons=true"
    />
  </picture>
</p>

In [ ]:
!kaggle datasets download -d busielmorley/worldcities-pop-lang-rank-sql-create-tbls

Dataset URL: https://www.kaggle.com/datasets/busielmorley/worldcities-pop-lang-rank-sql-create-tbls
License(s): world-bank
Downloading worldcities-pop-lang-rank-sql-create-tbls.zip to /content
100% 89.9k/89.9k [00:00<00:00, 78.3MB/s]

# install XAMPP first, upload SQL database and then Run the following code in jupitar notebook.

In [ ]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="",
    database="world"
)

print(conn)

In [ ]:
import pandas as pd

pd.read_sql("SELECT * FROM city", conn)

## Working with APIs

In [2]:
import pandas as pd

In [6]:
import http.client

conn = http.client.HTTPSConnection("indeed-scraper-api.p.rapidapi.com")

payload = "{\"scraper\":{\"maxRows\":15,\"query\":\"Developer\",\"location\":\"San Francisco\",\"jobType\":\"fulltime\",\"radius\":\"50\",\"sort\":\"relevance\",\"fromDays\":\"7\",\"country\":\"us\"}}"

headers = {
    'x-rapidapi-key': "b64c480237msh8ab652c8f37e954p1fff34jsn0e857e58d76f",
    'x-rapidapi-host': "indeed-scraper-api.p.rapidapi.com",
    'Content-Type': "application/json"
}

conn.request("POST", "/api/job", payload, headers)

res = conn.getresponse()
data = res.read()

print(data.decode("utf-8"))

final_data = data.decode("utf-8")

{"state":"completed","meta":{"max_rows_per_request":15,"note":"Results limited to 15 jobs per request. For unlimited access, contact us: https://borderline.cloud"},"name":"indeed-scraper-queue","data":{"scraper":{"maxRows":15,"query":"Developer","location":"San Francisco","jobType":"fulltime","radius":"50","sort":"relevance","fromDays":"7","country":"us"}},"id":"h8u88r2p7qq9ms8yndwnd3u8","progress":0,"returnvalue":{"data":[{"jobKey":"d68a1b07ae3ac1e2","scrapingInfo":{"page":1,"index":10},"title":"NPI Product Manager-Power Supply /Hardware ( Mandarin Required)","jobType":["Full-time"],"descriptionHtml":"<p><b>About Us:</b></p><p>MEAN WELL USA is a subsidiary of the globally renowned MEAN WELL group, a worldwide leading standard POWER SUPPLY manufacturer in the world . With over 13,000 standard off-the-shelf models, enabling us to offer a total power supply solution that satisfy customer's requirements. Established in the Bay Area of California &ndash; Fremont in 1999, MEAN WELL USA stands as a beacon of excellence in the power supply industry. We are looking for a self-motivated and results-oriented individual who can successfully manage company&rsquo;s distribution business. This is a great opportunity to join one of the leading standards switching power supply manufacturers in the world.</p><p><b>Job Description:</b></p><p>We are seeking a dynamic and experienced Product Manager to join our team at MEAN WELL. As a Product Manager, you will play a crucial role in defining and executing the product strategy to drive growth and innovation in our power supply product line. This role requires a blend of technical expertise in power supply technologies, strong market understanding, and exceptional project management skills.</p><p><b>Job Responsibilities:</b></p><p>1. Product Strategy Development</p><p>o Conduct market research and analysis to identify customer needs, market trends, and competitive landscape in the power supply industry,</p><p>o Define and prioritize product features and enhancements based on customer feedback and business objectives,</p><p>o Develop a clear product roadmap and strategy aligned with company goals and market opportunities,</p><p>o Perform internal and external trainings to educate, demonstrate, and advocate new products and market technologies.</p><p>2. Product Lifecycle Management</p><p>o Participate in the management of product development specific for the local market,</p><p>o Manage the entire product lifecycle from concept to launch to end-of-life,</p><p>o Collaborate with cross-functional teams including engineering, manufacturing, sales, and marketing to ensure successful product development and launch,</p><p>o Develop comprehensive go-to-market plans for new product launches and existing product updates.</p><p>3. Customer Engagement and Relationship Management</p><p>o Act as the voice of the customer within the organization, advocating for customer needs and preferences,</p><p>o Build strong relationships with key customers and partners to gather insights and feedback,</p><p>o Conduct customer surveys, market demand research, and feasibility studies to validate product ideas and gather requirements.</p><p>4. Performance Monitoring and Optimization</p><p>o Define key performance indicators (KPIs) to measure the success of product initiatives,</p><p>o Monitor and analyze product performance, user feedback, and market trends to identify areas for improvement and optimization,</p><p>o Market data-driven decisions and iterate on products to enhance customer satisfaction and business outcomes.</p><p><b>Job Requirements:</b></p><p>&middot; A bachelor&rsquo;s degree in Engineering (Electrical, Mechanical, Computer Science) or other applicable technical degree is required</p><p>&middot; 2+ years of experience as a Product Manager or similar role in the power supply and its related industries,</p><p>&middot; Strong understanding of power supply technologies, including AC-DC and DC-DC converters, inverters, and AC-AC VFDs,</p><p>&middot; Demonstrated success in developing and launching products that meet customer needs and business objectives,</p><p>&middot; Excellent project management skills with the ability to manage multiple projects simultaneously,</p><p>&middot; Analytical mindset with proficiency in market research, competitive analysis, and SMART decision making,</p><p>&middot; Strong communication and interpersonal skills with the ability to collaborate effectively across teams and influence stakeholders,</p><p>&middot; Creative thinker with a passion for innovation and continuous improvement,</p><p>&middot; Proficiency with Microsoft Office tools is required, including Word, Excel, PowerPoint, etc.,</p><p>&middot; Proficiency with Chinese Mandarin is a plus.</p><p>Job Type: Full-time</p><p>Pay: $80,000.00 - $100,000.00 per year</p><p>Benefits:</p><ul><li>401(k)</li><li>401(k) matching</li><li>Dental insurance</li><li>Employee assistance program</li><li>Flexible spending account</li><li>Health insurance</li><li>Health savings account</li><li>Life insurance</li><li>Paid time off</li><li>Vision insurance</li></ul><p>Compensation Package:</p><ul><li>Bonus opportunities</li><li>Yearly bonus</li><li>Yearly pay</li></ul><p>Experience:</p><ul><li>Product management: 3 years (Preferred)</li></ul><p>Language:</p><ul><li>Mandarin (Required)</li></ul><p>Work Location: In person</p>","companyLogoUrl":"https://d2q79iu7y748jz.cloudfront.net/s/_squarelogo/256x256/e93f022cd012920b7d133885f2947cc5","descriptionText":"*About Us:*\n\nMEAN WELL USA is a subsidiary of the globally renowned MEAN WELL group, a worldwide leading standard POWER SUPPLY manufacturer in the world . With over 13,000 standard off-the-shelf models, enabling us to offer a total power supply solution that satisfy customer's requirements. Established in the Bay Area of California – Fremont in 1999, MEAN WELL USA stands as a beacon of excellence in the power supply industry. We are looking for a self-motivated and results-oriented individual who can successfully manage company’s distribution business. This is a great opportunity to join one of the leading standards switching power supply manufacturers in the world.\n\n*Job Description:*\n\nWe are seeking a dynamic and experienced Product Manager to join our team at MEAN WELL. As a Product Manager, you will play a crucial role in defining and executing the product strategy to drive growth and innovation in our power supply product line. This role requires a blend of technical expertise in power supply technologies, strong market understanding, and exceptional project management skills.\n\n*Job Responsibilities:*\n\n1. Product Strategy Development\n\no Conduct market research and analysis to identify customer needs, market trends, and competitive landscape in the power supply industry,\n\no Define and prioritize product features and enhancements based on customer feedback and business objectives,\n\no Develop a clear product roadmap and strategy aligned with company goals and market opportunities,\n\no Perform internal and external trainings to educate, demonstrate, and advocate new products and market technologies.\n\n2. Product Lifecycle Management\n\no Participate in the management of product development specific for the local market,\n\no Manage the entire product lifecycle from concept to launch to end-of-life,\n\no Collaborate with cross-functional teams including engineering, manufacturing, sales, and marketing to ensure successful product development and launch,\n\no Develop comprehensive go-to-market plans for new product launches and existing product updates.\n\n3. Customer Engagement and Relationship Management\n\no Act as the voice of the customer within the organization, advocating for customer needs and preferences,\n\no Build strong relationships with key customers and partners to gather insights and feedback,\n\no Conduct customer surveys, market demand research, and feasibility studies to validate product ideas and gather requirements.\n\n4. Performance Monitoring and Optimization\n\no Define key performance indicators (KPIs) to measure the success of product initiatives,\n\no Monitor and analyze product performance, user feedback, and market trends to identify areas for improvement and optimization,\n\no Market data-driven decisions and iterate on products to enhance customer satisfaction and business outcomes.\n\n*Job Requirements:*\n\n· A bachelor’s degree in Engineering (Electrical, Mechanical, Computer Science) or other applicable technical degree is required\n\n· 2+ years of experience as a Product Manager or similar role in the power supply and its related industries,\n\n· Strong understanding of power supply technologies, including AC-DC and DC-DC converters, inverters, and AC-AC VFDs,\n\n· Demonstrated success in developing and launching products that meet customer needs and business objectives,\n\n· Excellent project management skills with the ability to manage multiple projects simultaneously,\n\n· Analytical mindset with proficiency in market research, competitive analysis, and SMART decision making,\n\n· Strong communication and interpersonal skills with the ability to collaborate effectively across teams and influence stakeholders,\n\n· Creative thinker with a passion for innovation and continuous improvement,\n\n· Proficiency with Microsoft Office tools is required, including Word, Excel, PowerPoint, etc.,\n\n· Proficiency with Chinese Mandarin is a plus.\n\nJob Type: Full-time\n\nPay: $80,000.00 - $100,000.00 per year\n\nBenefits:\n* 401(k)\n* 401(k) matching\n* Dental insurance\n* Employee assistance program\n* Flexible spending account\n* Health insurance\n* Health savings account\n* Life insurance\n* Paid time off\n* Vision insurance\nCompensation Package:\n* Bonus opportunities\n* Yearly bonus\n* Yearly pay\n\n\n\nExperience:\n* Product management: 3 years (Preferred)\n\nLanguage:\n* Mandarin (Required)\n\nWork Location: In person","companyName":"Mean Well USA Inc.","companyUrl":"https://www.indeed.com/cmp/Mean-Well-USA-Inc.-1","companyHeaderUrl":"https://d2q79iu7y748jz.cloudfront.net/s/_headerimage/1960x400/d3329e279f3af3c2e50e6f51fd452758","location":{"city":"Fremont","postalCode":"94538","country":"United States","countryCode":"US","formattedAddressLong":"Fremont, CA 94538","formattedAddressShort":"Fremont, CA","latitude":37.50783,"longitude":-121.94902,"streetAddress":"44030 Fremont Boulevard","fullAddress":"44030 Fremont Boulevard, Fremont, CA 94538"},"salary":{"salaryCurrency":"USD","salaryMax":100000,"salaryMin":80000,"salarySource":"EXTRACTION","salaryText":"$80,000 - $100,000 a year","salaryType":"yearly"},"rating":{"rating":4.3,"count":9},"benefits":["Health savings account","Health insurance","Dental insurance","401(k)","Flexible spending account","Paid time off","Employee assistance program","Vision insurance","401(k) matching","Life insurance"],"occupation":["Technology Occupations","Technology Management Occupations","Technical Product Managers & Owners"],"attributes":["Roadmap creation (System development task)","Performance monitoring","Mandarin","Bachelor’s degree in mechanical engineering","Feature prioritization","Customer communication","New product introduction engineering projects","Product development project management","Microsoft Excel","Customer relationship building","Market research within energy industry","Computer Science","Requirements specification","Requirements design","Health savings account","Bachelor's degree in electrical engineering","Conducting user feedback sessions","Product marketing","Product marketing strategy","Identifying new business opportunities","Engineering","Competitive analysis","Customer satisfaction tracking","Mechanical Engineering","Yearly bonus","Full-time","Yearly pay","Office","Client relationship development","Marketing product development","Health insurance","Product vision management","Dental insurance","401(k)","Flexible spending account","Key Performance Indicators","Collaboration with product development teams","Analysis skills","Bachelor’s degree in engineering","Paid time off","Continuous improvement","Decision making","Product management","Industry trends","Requirements analysis","Product line strategy","Customer engagement","Customer relationship management","US work authorization","Bonus opportunities","Requirements management","Data-driven problem-solving","Collaboration with manufacturing teams","Research data analysis","Employee assistance program","Product strategy","User research for product design","Vision insurance","Productivity software","401(k) matching","In-person","Customer satisfaction improvement","Senior level","Electrical Engineering","Training","Bachelor's degree in computer science","Go-to-market strategy","2 years","Communication skills","Technical Proficiency","Project stakeholder communication","Market research within technology industry","Life insurance","Stakeholder relationship building","Cross-functional communication","Technical product management within tech","Customer surveys"],"contacts":[],"shifts":[],"socialInsurance":["Health insurance"],"workingSystem":[],"shiftAndSchedule":[],"postedToday":false,"hiringDemand":{"isHighVolumeHiring":false,"isUrgentHire":false},"datePublished":"2026-05-29","expired":false,"source":"Indeed","age":"14 hours ago","isRemote":false,"locale":"us","language":"en","jobUrl":"https://www.indeed.com/viewjob?jk=d68a1b07ae3ac1e2","applyUrl":"http://www.indeed.com/job/npi-product-manager-power-supply-hardware-mandarin-required-d68a1b07ae3ac1e2","emails":[],"companyIndustry":"INDUSTRIAL_MANUFACTURING","companyAddresses":["44030 Fremont Blvd. \r\nFremont, CA 94538"],"companyNumEmployees":"11 to 50","companyRevenue":"$25M to $100M (USD)","companyDescription":"MEAN WELL is a leading standard switching power supply manufacturer in the world having more than 10,000 standard off-the-shelf models enabling us to offer a total power supply solution that satisfy customer's requirements - Specializing in design, manufacturing, and marketing AC-DC switching power supplies, DC-DC converters, DC-AC inverters and adapters/battery chargers for global markets. With average annual growth of 15-20% and over 2,000 employees, MEAN WELL continues its path toward a healthy future.\r\n\r\n MEAN WELL USA is a subsidiary of MEAN WELL group, a worldwide leading standard POWER SUPPLY manufacturer. MEAN WELL USA was established in 1999 and is located in the BAY AREA of California - Fremont. Our professionally trained teams provide local and prompt support to the customers and partners in North America for their power supply needs. There are two other offices in CENTRAL (Kansas City, MO) and in EAST (Mt. Laurel, NJ) to serve locally. The CENTRAL KCMO office also provides value-added services for flexible modifications and power solutions.","companyFounded":{"year":1999},"companyLinks":{"facebook":null,"instagram":null,"twitter":null,"customLinks":[],"corporateWebsite":"http://meanwellusa.com/"},"companyCeo":{"name":null,"photoUrl":null,"startDate":null},"requirements":[{"label":"Microsoft Excel","requirementSeverity":"REQUIRED"},{"label":"Product strategy","requirementSeverity":"PREFERRED"},{"label":"Electrical Engineering","requirementSeverity":"PREFERRED"},{"label":"Product marketing","requirementSeverity":"PREFERRED"},{"label":"Requirements analysis","requirementSeverity":"PREFERRED"}]},{"jobKey":"1edbedada46a970f","scrapingInfo":{"page":1,"index":6},"title":"AI Infrastructure Engineer, Digital Optimus","jobType":["Full-time"],"descriptionHtml":"<div><b>What to Expect</b><div>\nDigital Optimus is the software counterpart to our physical humanoid, designed to interact with computer interfaces and perform long-horizon agentic behaviors. Our approach is modeled after real-time control policies rather than screenshot-based VLM agents, with the larger goal of integrating with Tesla's broader AI ecosystem. We're seeking an ML/RL Infra Engineer to build scalable, reliable infrastructure that powers these agents and enables seamless, high-volume rollouts for model evaluation &amp; RL training. Top candidates will have deep experience in large-scale ML systems, high-performance training, and edge deployment, though evidence of exceptional ability matters more than relevance alone.</div><br>\n<b>\nWhat You'll Do</b><div><ul><li>\nDesign &amp; implement scalable distributed training infrastructure for large agentic models, supporting imitation learning, reinforcement learning (online &amp; offline), and long-horizon training workflows</li><li>\nBuild high-fidelity, ultra-realistic training &amp; simulation environments capable of handling complex, interruptible, long-context agent trajectories at massive scale</li><li>\nOptimize ML and RL training pipelines for throughput, cost-efficiency, and reliability across multi-node GPU clusters</li><li>\nImplement advanced model serving, quantization, distillation, and deployment strategies tailored for Tesla&rsquo;s hardware platforms</li><li>\nCollaborate with research, AI engineering, and production teams to productionize agent systems and integrate them with Tesla&rsquo;s autonomy (FSD) and robotics (Optimus) platforms</li><li>\nDesign systems for efficient context management, checkpointing, and orchestration of long-horizon agentic workloads</li><li>\nContinuously improve developer velocity through better tooling, CI/CD for ML, experiment tracking, and reproducible training environments</li></ul></div><br>\n<b>\nWhat You'll Bring</b><div><ul><li>\nExperience in ML infrastructure, large-scale distributed systems, or high-performance computing for deep learning/reinforcement learning</li><li>\nStrong expertise with training frameworks (PyTorch, JAX, DeepSpeed, FSDP, Megatron, etc.) and distributed training at scale</li><li>\nDeep knowledge of GPU/accelerator optimization, model parallelism, quantization, and edge deployment</li><li>\nProficiency in Python, Kubernetes, cloud infrastructure (or on-prem clusters), and modern MLOps practices</li><li>\nExperience building data pipelines and simulation environments for reinforcement learning or robotics applications is highly valued</li><li>\nStrong software engineering fundamentals, system design skills, and a passion for building reliable, observable, and high-performance ML platforms</li><li>\nAbility to work effectively in a fast-paced, cross-functional environment with researchers and engineers</li></ul></div><br>\n<b>\nCompensation and Benefits</b><div>\nBenefits</div><div><p>\nAlong with competitive pay, as a full-time Tesla employee, you are eligible for the following benefits at day 1 of hire:</p>\n<ul><li>Medical plans &gt; plan options with $0 payroll deduction</li>\n<li>Family-building, fertility, adoption and surrogacy benefits</li>\n<li>Dental (including orthodontic coverage) and vision plans, both have options with a $0 paycheck contribution</li>\n<li>Company Paid (Health Savings Accounts) HSA Contribution when enrolled in the High-Deductible medical plan with HSA</li>\n<li>Healthcare and Dependent Care Flexible Spending Accounts (FSA)</li>\n<li>401(k) with employer match, Employee Stock Purchase Plans, and other financial benefits</li>\n<li>Company paid Basic Life, AD&amp;D</li><li>\nShort-term and long-term disability insurance (90 day waiting period)</li>\n<li>Employee Assistance Program</li>\n<li>Sick and Vacation time (Flex time for salary positions, Accrued hours for Hourly positions), and Paid Holidays</li>\n<li>Back-up childcare and parenting support resources</li>\n<li>Voluntary benefits to include: critical illness, hospital indemnity, accident insurance, theft &amp; legal services, and pet insurance</li>\n<li>Weight Loss and Tobacco Cessation Programs</li>\n<li>Tesla Babies program</li>\n<li>Commuter benefits</li>\n<li>Employee discounts and perks program</li>\n</ul></div><div>Expected Compensation</div><div>\n$140,000 - $252,000/annual salary + cash

In [13]:
import json
response = json.loads(final_data)
print(json.dumps(response, indent=2)[:5000])

{
  "state": "completed",
  "meta": {
    "max_rows_per_request": 15,
    "note": "Results limited to 15 jobs per request. For unlimited access, contact us: https://borderline.cloud"
  },
  "name": "indeed-scraper-queue",
  "data": {
    "scraper": {
      "maxRows": 15,
      "query": "Developer",
      "location": "San Francisco",
      "jobType": "fulltime",
      "radius": "50",
      "sort": "relevance",
      "fromDays": "7",
      "country": "us"
    }
  },
  "id": "h8u88r2p7qq9ms8yndwnd3u8",
  "progress": 0,
  "returnvalue": {
    "data": [
      {
        "jobKey": "d68a1b07ae3ac1e2",
        "scrapingInfo": {
          "page": 1,
          "index": 10
        },
        "title": "NPI Product Manager-Power Supply /Hardware ( Mandarin Required)",
        "jobType": [
          "Full-time"
        ],
        "descriptionHtml": "<p><b>About Us:</b></p><p>MEAN WELL USA is a subsidiary of the globally renowned MEAN WELL group, a worldwide leading standard POWER SUPPLY manufacturer in the world . With over 13,000 standard off-the-shelf models, enabling us to offer a total power supply solution that satisfy customer's requirements. Established in the Bay Area of California &ndash; Fremont in 1999, MEAN WELL USA stands as a beacon of excellence in the power supply industry. We are looking for a self-motivated and results-oriented individual who can successfully manage company&rsquo;s distribution business. This is a great opportunity to join one of the leading standards switching power supply manufacturers in the world.</p><p><b>Job Description:</b></p><p>We are seeking a dynamic and experienced Product Manager to join our team at MEAN WELL. As a Product Manager, you will play a crucial role in defining and executing the product strategy to drive growth and innovation in our power supply product line. This role requires a blend of technical expertise in power supply technologies, strong market understanding, and exceptional project management skills.</p><p><b>Job Responsibilities:</b></p><p>1. Product Strategy Development</p><p>o Conduct market research and analysis to identify customer needs, market trends, and competitive landscape in the power supply industry,</p><p>o Define and prioritize product features and enhancements based on customer feedback and business objectives,</p><p>o Develop a clear product roadmap and strategy aligned with company goals and market opportunities,</p><p>o Perform internal and external trainings to educate, demonstrate, and advocate new products and market technologies.</p><p>2. Product Lifecycle Management</p><p>o Participate in the management of product development specific for the local market,</p><p>o Manage the entire product lifecycle from concept to launch to end-of-life,</p><p>o Collaborate with cross-functional teams including engineering, manufacturing, sales, and marketing to ensure successful product development and launch,</p><p>o Develop comprehensive go-to-market plans for new product launches and existing product updates.</p><p>3. Customer Engagement and Relationship Management</p><p>o Act as the voice of the customer within the organization, advocating for customer needs and preferences,</p><p>o Build strong relationships with key customers and partners to gather insights and feedback,</p><p>o Conduct customer surveys, market demand research, and feasibility studies to validate product ideas and gather requirements.</p><p>4. Performance Monitoring and Optimization</p><p>o Define key performance indicators (KPIs) to measure the success of product initiatives,</p><p>o Monitor and analyze product performance, user feedback, and market trends to identify areas for improvement and optimization,</p><p>o Market data-driven decisions and iterate on products to enhance customer satisfaction and business outcomes.</p><p><b>Job Requirements:</b></p><p>&middot; A bachelor&rsquo;s degree in Engineering (Electrical, Mechanical, Computer Science) or other applicable technical degree is required</p><p>&middot; 2+ years of experience as a Product Manager or similar role in the power supply and its related industries,</p><p>&middot; Strong understanding of power supply technologies, including AC-DC and DC-DC converters, inverters, and AC-AC VFDs,</p><p>&middot; Demonstrated success in developing and launching products that meet customer needs and business objectives,</p><p>&middot; Excellent project management skills with the ability to manage multiple projects simultaneously,</p><p>&middot; Analytical mindset with proficiency in market research, competitive analysis, and SMART decision making,</p><p>&middot; Strong communication and interpersonal skills with the ability to collaborate effectively across teams and influence stakeholders,</p><p>&middot; Creative thinker with a passion for innovation and continuous improvement,</p><p>&middot; Proficiency with Microsoft Office tools is required, including Word, Excel, PowerPoint, etc.,</p><p>&middot; Proficiency with Chinese Ma

In [14]:
fprint(type(response))
print(response.keys())

<class 'dict'>
dict_keys(['state', 'meta', 'name', 'data', 'id', 'progress', 'returnvalue', 'delay', 'priority', 'attemptsStarted', 'attemptsMade', 'stalledCounter', 'timestamp', 'finishedOn', 'processedOn'])

In [18]:
response['returnvalue']['data']

[{'jobKey': 'd68a1b07ae3ac1e2',
  'scrapingInfo': {'page': 1, 'index': 10},
  'title': 'NPI Product Manager-Power Supply /Hardware ( Mandarin Required)',
  'jobType': ['Full-time'],
  'descriptionHtml': "<p><b>About Us:</b></p><p>MEAN WELL USA is a subsidiary of the globally renowned MEAN WELL group, a worldwide leading standard POWER SUPPLY manufacturer in the world . With over 13,000 standard off-the-shelf models, enabling us to offer a total power supply solution that satisfy customer's requirements. Established in the Bay Area of California &ndash; Fremont in 1999, MEAN WELL USA stands as a beacon of excellence in the power supply industry. We are looking for a self-motivated and results-oriented individual who can successfully manage company&rsquo;s distribution business. This is a great opportunity to join one of the leading standards switching power supply manufacturers in the world.</p><p><b>Job Description:</b></p><p>We are seeking a dynamic and experienced Product Manager to join our team at MEAN WELL. As a Product Manager, you will play a crucial role in defining and executing the product strategy to drive growth and innovation in our power supply product line. This role requires a blend of technical expertise in power supply technologies, strong market understanding, and exceptional project management skills.</p><p><b>Job Responsibilities:</b></p><p>1. Product Strategy Development</p><p>o Conduct market research and analysis to identify customer needs, market trends, and competitive landscape in the power supply industry,</p><p>o Define and prioritize product features and enhancements based on customer feedback and business objectives,</p><p>o Develop a clear product roadmap and strategy aligned with company goals and market opportunities,</p><p>o Perform internal and external trainings to educate, demonstrate, and advocate new products and market technologies.</p><p>2. Product Lifecycle Management</p><p>o Participate in the management of product development specific for the local market,</p><p>o Manage the entire product lifecycle from concept to launch to end-of-life,</p><p>o Collaborate with cross-functional teams including engineering, manufacturing, sales, and marketing to ensure successful product development and launch,</p><p>o Develop comprehensive go-to-market plans for new product launches and existing product updates.</p><p>3. Customer Engagement and Relationship Management</p><p>o Act as the voice of the customer within the organization, advocating for customer needs and preferences,</p><p>o Build strong relationships with key customers and partners to gather insights and feedback,</p><p>o Conduct customer surveys, market demand research, and feasibility studies to validate product ideas and gather requirements.</p><p>4. Performance Monitoring and Optimization</p><p>o Define key performance indicators (KPIs) to measure the success of product initiatives,</p><p>o Monitor and analyze product performance, user feedback, and market trends to identify areas for improvement and optimization,</p><p>o Market data-driven decisions and iterate on products to enhance customer satisfaction and business outcomes.</p><p><b>Job Requirements:</b></p><p>&middot; A bachelor&rsquo;s degree in Engineering (Electrical, Mechanical, Computer Science) or other applicable technical degree is required</p><p>&middot; 2+ years of experience as a Product Manager or similar role in the power supply and its related industries,</p><p>&middot; Strong understanding of power supply technologies, including AC-DC and DC-DC converters, inverters, and AC-AC VFDs,</p><p>&middot; Demonstrated success in developing and launching products that meet customer needs and business objectives,</p><p>&middot; Excellent project management skills with the ability to manage multiple projects simultaneously,</p><p>&middot; Analytical mindset with proficiency in market research, competitive analysis, and SMART decision making,</p><p>&middot; Strong communication and interpersonal skills with the ability to collaborate effectively across teams and influence stakeholders,</p><p>&middot; Creative thinker with a passion for innovation and continuous improvement,</p><p>&middot; Proficiency with Microsoft Office tools is required, including Word, Excel, PowerPoint, etc.,</p><p>&middot; Proficiency with Chinese Mandarin is a plus.</p><p>Job Type: Full-time</p><p>Pay: $80,000.00 - $100,000.00 per year</p><p>Benefits:</p><ul><li>401(k)</li><li>401(k) matching</li><li>Dental insurance</li><li>Employee assistance program</li><li>Flexible spending account</li><li>Health insurance</li><li>Health savings account</li><li>Life insurance</li><li>Paid time off</li><li>Vision insurance</li></ul><p>Compensation Package:</p><ul><li>Bonus opportunities</li><li>Yearly bonus</li><li>Yearly pay</li></ul><p>Experience:</p><ul><li>Product management: 3 years (Preferred)</li></ul><p>Language:</p><ul><li>Mandarin (Required)</li></ul><p>Work Location: In person</p>",
  'companyLogoUrl': 'https://d2q79iu7y748jz.cloudfront.net/s/_squarelogo/256x256/e93f022cd012920b7d133885f2947cc5',
  'descriptionText': "*About Us:*\n\nMEAN WELL USA is a subsidiary of the globally renowned MEAN WELL group, a worldwide leading standard POWER SUPPLY manufacturer in the world . With over 13,000 standard off-the-shelf models, enabling us to offer a total power supply solution that satisfy customer's requirements. Established in the Bay Area of California – Fremont in 1999, MEAN WELL USA stands as a beacon of excellence in the power supply industry. We are looking for a self-motivated and results-oriented individual who can successfully manage company’s distribution business. This is a great opportunity to join one of the leading standards switching power supply manufacturers in the world.\n\n*Job Description:*\n\nWe are seeking a dynamic and experienced Product Manager to join our team at MEAN WELL. As a Product Manager, you will play a crucial role in defining and executing the product strategy to drive growth and innovation in our power supply product line. This role requires a blend of technical expertise in power supply technologies, strong market understanding, and exceptional project management skills.\n\n*Job Responsibilities:*\n\n1. Product Strategy Development\n\no Conduct market research and analysis to identify customer needs, market trends, and competitive landscape in the power supply industry,\n\no Define and prioritize product features and enhancements based on customer feedback and business objectives,\n\no Develop a clear product roadmap and strategy aligned with company goals and market opportunities,\n\no Perform internal and external trainings to educate, demonstrate, and advocate new products and market technologies.\n\n2. Product Lifecycle Management\n\no Participate in the management of product development specific for the local market,\n\no Manage the entire product lifecycle from concept to launch to end-of-life,\n\no Collaborate with cross-functional teams including engineering, manufacturing, sales, and marketing to ensure successful product development and launch,\n\no Develop comprehensive go-to-market plans for new product launches and existing product updates.\n\n3. Customer Engagement and Relationship Management\n\no Act as the voice of the customer within the organization, advocating for customer needs and preferences,\n\no Build strong relationships with key customers and partners to gather insights and feedback,\n\no Conduct customer surveys, market demand research, and feasibility studies to validate product ideas and gather requirements.\n\n4. Performance Monitoring and Optimization\n\no Define key performance indicators (KPIs) to measure the success of product initiatives,\n\no Monitor and analyze product performance, user feedback, and market trends to identify areas for improvement and optimization,\n\no Market data-driven decisions and iterate on products to enhance customer satisfaction and business outcomes.\n\n*Job Requirements:*\n\n· A bachelor’s degree in Engineering (Electrical, Mechanical, Computer Science) or other applicable technical degree is required\n\n· 2+ years of experience as a Product Manager or similar role in the power supply and its related industries,\n\n· Strong understanding of power supply technologies, including AC-DC and DC-DC converters, inverters, and AC-AC VFDs,\n\n· Demonstrated success in developing and launching products that meet customer needs and business objectives,\n\n· Excellent project management skills with the ability to manage multiple projects simultaneously,\n\n· Analytical mindset with proficiency in market research, competitive analysis, and SMART decision making,\n\n· Strong communication and interpersonal skills with the ability to collaborate effectively across teams and influence stakeholders,\n\n· Creative thinker with a passion for innovation and continuous improvement,\n\n· Proficiency with Microsoft Office tools is required, including Word, Excel, PowerPoint, etc.,\n\n· Proficiency with Chinese Mandarin is a plus.\n\nJob Type: Full-time\n\nPay: $80,000.00 - $100,000.00 per year\n\nBenefits:\n* 401(k)\n* 401(k) matching\n* Dental insurance\n* Employee assistance program\n* Flexible spending account\n* Health insurance\n* Health savings account\n* Life insurance\n* Paid time off\n* Vision insurance\nCompensation Package:\n* Bonus opportunities\n* Yearly bonus\n* Yearly pay\n\n\n\nExperience:\n* Product management: 3 years (Preferred)\n\nLanguage:\n* Mandarin (Required)\n\nWork Location: In person",
  'companyName': 'Mean Well USA Inc.',
  'companyUrl': 'https://www.indeed.com/cmp/Mean-Well-USA-Inc.-1',
  'companyHeaderUrl': 'https://d2q79iu7y748jz.cloudfront.net/s/_headerimage/1960x400/d3329e279f3af3c2e50e6f51fd452758',
  'location': {'city': 'Fremont',
   'postalCode': '94538',
   'country': 'United States',
   'countryCode': 'US',
   'formattedAddressLong': 'Fremont, CA 94538',
   'formattedAddressShort': 'Fremont, CA',
   'latitude': 37.50783,
   'longitude': -121.94902,
   'streetAddress': '44030 Fremont Boulevard',
   'fullAddress': '44030 Fremont Boulevard, Fremont, CA 94538'},
  'salary': {'salaryCurrency': 'USD',
   'salaryMax': 100000,
   'salaryMin': 80000,
   'salarySource': 'EXTRACTION',
   'salaryText': '$80,000 - $100,000 a year',
   'salaryType': 'yearly'},
  'rating': {'rating': 4.3, 'count': 9},
  'benefits': ['Health savings account',
   'Health insurance',
   'Dental insurance',
   '401(k)',
   'Flexible spending account',
   'Paid time off',
   'Employee assistance program',
   'Vision insurance',
   '401(k) matching',
   'Life insurance'],
  'occupation': ['Technology Occupations',
   'Technology Management Occupations',
   'Technical Product Managers & Owners'],
  'attributes': ['Roadmap creation (System development task)',
   'Performance monitoring',
   'Mandarin',
   'Bachelor’s degree in mechanical engineering',
   'Feature prioritization',
   'Customer communication',
   'New product introduction engineering projects',
   'Product development project management',
   'Microsoft Excel',
   'Customer relationship building',
   'Market research within energy industry',
   'Computer Science',
   'Requirements specification',
   'Requirements design',
   'Health savings account',
   "Bachelor's degree in electrical engineering",
   'Conducting user feedback sessions',
   'Product marketing',
   'Product marketing strategy',
   'Identifying new business opportunities',
   'Engineering',
   'Competitive analysis',
   'Customer satisfaction tracking',
   'Mechanical Engineering',
   'Yearly bonus',
   'Full-time',
   'Yearly pay',
   'Office',
   'Client relationship development',
   'Marketing product development',
   'Health insurance',
   'Product vision management',
   'Dental insurance',
   '401(k)',
   'Flexible spending account',
   'Key Performance Indicators',
   'Collaboration with product development teams',
   'Analysis skills',
   'Bachelor’s degree in engineering',
   'Paid time off',
   'Continuous improvement',
   'Decision making',
   'Product management',
   'Industry trends',
   'Requirements analysis',
   'Product line strategy',
   'Customer engagement',
   'Customer relationship management',
   'US work authorization',
   'Bonus opportunities',
   'Requirements management',
   'Data-driven problem-solving',
   'Collaboration with manufacturing teams',
   'Research data analysis',
   'Employee assistance program',
   'Product strategy',
   'User research for product design',
   'Vision insurance',
   'Productivity software',
   '401(k) matching',
   'In-person',
   'Customer satisfaction improvement',
   'Senior level',
   'Electrical Engineering',
   'Training',
   "Bachelor's degree in computer science",
   'Go-to-market strategy',
   '2 years',
   'Communication skills',
   'Technical Proficiency',
   'Project stakeholder communication',
   'Market research within technology industry',
   'Life insurance',
   'Stakeholder relationship building',
   'Cross-functional communication',
   'Technical product management within tech',
   'Customer surveys'],
  'contacts': [],
  'shifts': [],
  'socialInsurance': ['Health insurance'],
  'workingSystem': [],
  'shiftAndSchedule': [],
  'postedToday': False,
  'hiringDemand': {'isHighVolumeHiring': False, 'isUrgentHire': False},
  'datePublished': '2026-05-29',
  'expired': False,
  'source': 'Indeed',
  'age': '14 hours ago',
  'isRemote': False,
  'locale': 'us',
  'language': 'en',
  'jobUrl': 'https://www.indeed.com/viewjob?jk=d68a1b07ae3ac1e2',
  'applyUrl': 'http://www.indeed.com/job/npi-product-manager-power-supply-hardware-mandarin-required-d68a1b07ae3ac1e2',
  'emails': [],
  'companyIndustry': 'INDUSTRIAL_MANUFACTURING',
  'companyAddresses': ['44030 Fremont Blvd. \r\nFremont, CA 94538'],
  'companyNumEmployees': '11 to 50',
  'companyRevenue': '$25M to $100M (USD)',
  'companyDescription': "MEAN WELL is a leading standard switching power supply manufacturer in the world having more than 10,000 standard off-the-shelf models enabling us to offer a total power supply solution that satisfy customer's requirements - Specializing in design, manufacturing, and marketing AC-DC switching power supplies, DC-DC converters, DC-AC inverters and adapters/battery chargers for global markets. With average annual growth of 15-20% and over 2,000 employees, MEAN WELL continues its path toward a healthy future.\r\n\r\n MEAN WELL USA is a subsidiary of MEAN WELL group, a worldwide leading standard POWER SUPPLY manufacturer. MEAN WELL USA was established in 1999 and is located in the BAY AREA of California - Fremont. Our professionally trained teams provide local and prompt support to the customers and partners in North America for their power supply needs. There are two other offices in CENTRAL (Kansas City, MO) and in EAST (Mt. Laurel, NJ) to serve locally. The CENTRAL KCMO office also provides value-added services for flexible modifications and power solutions.",
  'companyFounded': {'year': 1999},
  'companyLinks': {'facebook': None,
   'instagram': None,
   'twitter': None,
   'customLinks': [],
   'corporateWebsite': 'http://meanwellusa.com/'},
  'companyCeo': {'name': None, 'photoUrl': None, 'startDate': None},
  'requirements': [{'label': 'Microsoft Excel',
    'requirementSeverity': 'REQUIRED'},
   {'label': 'Product strategy', 'requirementSeverity': 'PREFERRED'},
   {'label': 'Electrical Engineering', 'requirementSeverity': 'PREFERRED'},
   {'label': 'Product marketing', 'requirementSeverity': 'PREFERRED'},
   {'label': 'Requirements analysis', 'requirementSeverity': 'PREFERRED'}]},
 {'jobKey': '1edbedada46a970f',
  'scrapingInfo': {'page': 1, 'index': 6},
  'title': 'AI Infrastructure Engineer, Digital Optimus',
  'jobType': ['Full-time'],

In [30]:
response['returnvalue']['data'][0].keys()

dict_keys(['jobKey', 'scrapingInfo', 'title', 'jobType', 'descriptionHtml', 'companyLogoUrl', 'descriptionText', 'companyName', 'companyUrl', 'companyHeaderUrl', 'location', 'salary', 'rating', 'benefits', 'occupation', 'attributes', 'contacts', 'shifts', 'socialInsurance', 'workingSystem', 'shiftAndSchedule', 'postedToday', 'hiringDemand', 'datePublished', 'expired', 'source', 'age', 'isRemote', 'locale', 'language', 'jobUrl', 'applyUrl', 'emails', 'companyIndustry', 'companyAddresses', 'companyNumEmployees', 'companyRevenue', 'companyDescription', 'companyFounded', 'companyLinks', 'companyCeo', 'requirements'])

In [34]:
a = pd.DataFrame(response['returnvalue']['data'])
a.shape

(15, 44)

In [35]:
a

,jobKey,scrapingInfo,title,jobType,descriptionHtml,companyLogoUrl,descriptionText,companyName,companyUrl,companyHeaderUrl,...,companyAddresses,companyNumEmployees,companyRevenue,companyDescription,companyFounded,companyLinks,companyCeo,requirements,companyBriefDescription,numOfCandidates
0,d68a1b07ae3ac1e2,"{'page': 1, 'index': 10}",NPI Product Manager-Power Supply /Hardware ( M...,[Full-time],<p><b>About Us:</b></p><p>MEAN WELL USA is a s...,https://d2q79iu7y748jz.cloudfront.net/s/_squar...,*About Us:*\n\nMEAN WELL USA is a subsidiary o...,Mean Well USA Inc.,https://www.indeed.com/cmp/Mean-Well-USA-Inc.-1,https://d2q79iu7y748jz.cloudfront.net/s/_heade...,...,"[44030 Fremont Blvd. \r\nFremont, CA 94538]",11 to 50,$25M to $100M (USD),MEAN WELL is a leading standard switching powe...,{'year': 1999},"{'facebook': None, 'instagram': None, 'twitter...","{'name': None, 'photoUrl': None, 'startDate': ...","[{'label': 'Microsoft Excel', 'requirementSeve...",NaN,NaN
1,1edbedada46a970f,"{'page': 1, 'index': 6}","AI Infrastructure Engineer, Digital Optimus",[Full-time],<div><b>What to Expect</b><div>\nDigital Optim...,https://d2q79iu7y748jz.cloudfront.net/s/_squar...,What to Expect\nDigital Optimus is the softwar...,Tesla,https://www.indeed.com/cmp/Tesla,https://d2q79iu7y748jz.cloudfront.net/s/_heade...,...,"[1 Tesla Road Austin, TX 78725]","10,000+",$5B to $10B (USD),Tesla is accelerating the world’s transition t...,{'year': 2003},{'facebook': 'https://www.facebook.com/TeslaMo...,"{'name': 'Elon Musk', 'photoUrl': 'https://d2q...",[],Tesla is accelerating the world’s transition t...,NaN
2,a23c086e4df1f983,"{'page': 1, 'index': 0}",Software Engineer III - Java Full Stack Developer,[Full-time],"<div>Are you an experienced, passionate pionee...",https://d2q79iu7y748jz.cloudfront.net/s/_squar...,"Are you an experienced, passionate pioneer in ...",Deloitte,https://www.indeed.com/cmp/Deloitte,https://d2q79iu7y748jz.cloudfront.net/s/_heade...,...,"[New York, NY]","10,000+",more than $10B (USD),Deloitte provides industry-leading audit & ass...,{'year': 1850},{'facebook': 'https://www.facebook.com/Deloitt...,"{'name': 'Joseph B. Ucuzoglu', 'photoUrl': 'ht...",[],"We’re a leading professional services firm, bu...",NaN
3,76ac8d7e5e2bebb7,"{'page': 1, 'index': 1}",Java Full Stack Developer-Software Engineer II,[Full-time],"<div>Are you an experienced, passionate pionee...",https://d2q79iu7y748jz.cloudfront.net/s/_squar...,"Are you an experienced, passionate pioneer in ...",Deloitte,https://www.indeed.com/cmp/Deloitte,https://d2q79iu7y748jz.cloudfront.net/s/_heade...,...,"[New York, NY]","10,000+",more than $10B (USD),Deloitte provides industry-leading audit & ass...,{'year': 1850},{'facebook': 'https://www.facebook.com/Deloitt...,"{'name': 'Joseph B. Ucuzoglu', 'photoUrl': 'ht...",[],"We’re a leading professional services firm, bu...",NaN
4,d085666277315020,"{'page': 1, 'index': 2}",Lead Full Stack Engineer PxE Consulting,[Full-time],"<div>As a Lead Full-stack Software Engineer , ...",https://d2q79iu7y748jz.cloudfront.net/s/_squar...,"As a Lead Full-stack Software Engineer , you w...",Deloitte,https://www.indeed.com/cmp/Deloitte,https://d2q79iu7y748jz.cloudfront.net/s/_heade...,...,"[New York, NY]","10,000+",more than $10B (USD),Deloitte provides industry-leading audit & ass...,{'year': 1850},{'facebook': 'https://www.facebook.com/Deloitt...,"{'name': 'Joseph B. Ucuzoglu', 'photoUrl': 'ht...",[],"We’re a leading professional services firm, bu...",NaN
5,fa015098833cab24,"{'page': 1, 'index': 3}",Lead ServiceNow Software Engineer,[Full-time],"<div>As a Lead ServiceNow Software Engineer , ...",https://d2q79iu7y748jz.cloudfront.net/s/_squar...,"As a Lead ServiceNow Software Engineer , you w...",Deloitte,https://www.indeed.com/cmp/Deloitte,https://d2q79iu7y748jz.cloudfront.net/s/_heade...,...,"[New York, NY]","10,000+",more than $10B (USD),Deloitte provides industry-leading audit & ass...,{'year': 1850},{'facebook': 'https://www.facebook.com/Deloitt...,"{'name': 'Joseph B. Ucuzoglu', 'photoUrl': 'ht...",[],"We’re a leading professional services firm, bu...",NaN
6,847fe695bd0da00e,"{'page': 1, 'index': 5}",Cyber Full-Stack Technical Software Engineer,[Full-time],<div>Drive strategic growth and transformation...,https://d2q79iu7y748jz.cloudfront.net/s/_squar...,Drive strategic growth and transformation for ...,Deloitte,https://www.indeed.com/cmp/Deloitte,https://d2q79iu7y748jz.cloudfront.net/s/_heade...,...,"[New York, NY]","10,000+",more than $10B (USD),Deloitte provides industry-leading audit & ass...,{'year': 1850},{'facebook': 'https://www.facebook.com/Deloitt...,"{'name': 'Joseph B. Ucuzoglu', 'photoUrl': 'ht...",[],"We’re a leading professional services firm, bu...",NaN
7,caef10e9b749da86,"{'page': 1, 'index': 4}","Staff Software Engineer, Distributed Systems, ...",[Full-time],<div><b>What to Expect</b><div>\nAs a Staff So...,https://d2q79iu7y748jz.cloudfront.net/s/_squar...,What to Expect\nAs a Staff Software Engineer o...,Tesla,https://www.indeed.com/cmp/Tesla,https://d2q79iu7y748jz.cloudfront.net/s/_heade...,...,"[1 Tesla Road Austin, TX 78725]","10,000+",$5B to $10B (USD),Tesla is accelerating the world’s transition t...,{'year': 2003},{'facebook': 'https://www.facebook.com/TeslaMo...,"{'name': 'Elon Musk', 'photoUrl': 'https://d2q...",[],Tesla is accelerating the world’s transition t...,NaN
8,7f642c610470a071,"{'page': 1, 'index': 13}",Senior DevOps Engineer – Data Engineering,"[Full-time, Remote]","<p>InnoVet Health, a small and growing busines...",https://d2q79iu7y748jz.cloudfront.net/s/_squar...,"InnoVet Health, a small and growing business t...","innoVet Health, LLC","https://www.indeed.com/cmp/Innovet-Health,-LLC",https://d2q79iu7y748jz.cloudfront.net/s/_heade...,...,[],NaN,NaN,InnoVet Health is an SVDOB-owned company. We a...,NaN,"{'facebook': None, 'instagram': None, 'twitter...","{'name': None, 'photoUrl': None, 'startDate': ...","[{'label': 'Version control', 'requirementSeve...",NaN,NaN
9,2ad6e31b84c878ab,"{'page': 1, 'index': 11}",Software Engineer,[Full-time],<b>Employer:</b> Siemens Industry Software Inc...,https://d2q79iu7y748jz.cloudfront.net/s/_squar...,Employer: Siemens Industry Software Inc.\n\nEm...,Siemens,https://www.indeed.com/cmp/Siemens,https://d2q79iu7y748jz.cloudfront.net/s/_heade...,...,"[Munich, Bavaria]","10,000+",more than $10B (USD),Siemens is a leading technology company focuse...,{'year': 1847},{'facebook': 'https://www.facebook.com/Siemens...,"{'name': 'Dr. Roland Busch ', 'photoUrl': 'htt...",[],We are a leading technology company - focused ...,NaN
10,546d0f30bf1c2889,"{'page': 1, 'index': 7}",Scientific Software Engineer - AI/ML for Hyper...,[Full-time],<div><div>Lawrence Berkeley National Laborator...,https://d2q79iu7y748jz.cloudfront.net/s/_squar...,Lawrence Berkeley National Laboratory’s (Berke...,Lawrence Berkeley National Laboratory,https://www.indeed.com/cmp/Lawrence-Berkeley-N...,NaN,...,"[Berkeley, CA]","5,001 to 10,000",$100M to $500M (USD),NaN,{'year': 1931},"{'facebook': None, 'instagram': None, 'twitter...","{'name': None, 'photoUrl': None, 'startDate': ...",[],NaN,NaN
11,2fcebee4f246ba08,"{'page': 1, 'index': 12}",Software Engineer – Full Stack 3D Graphics,[Full-time],<div><p><b>Job Description\n</b></p><p><b>DUTI...,https://d2q79iu7y748jz.cloudfront.net/s/_squar...,Job Description\n\nDUTIES: Develop and optimiz...,General Motors (GM),https://www.indeed.com/cmp/General-Motors-(gm)-1,https://d2q79iu7y748jz.cloudfront.net/s/_heade...,...,"[Detroit, MI]","10,000+",more than $10B (USD),"At GM, our vision is a world with Zero Crashes...",{'year': 1908},{'facebook': 'https://www.facebook.com/general...,"{'name': 'Mary T. Barra', 'photoUrl': 'https:/...",[],"We see a future with Zero Crashes, Zero Emissi...",NaN
12,07db5ef39334cd32,"{'page': 1, 'index': 8}",Product Manager,"[Full-time, Remote]",<p><b>**Completion of all pre-screening questi...,NaN,*\*\*Completion of all pre-screening questions...,TrueLearn,https://www.indeed.com/cmp/Truelearn,NaN,...,[],NaN,NaN,NaN,NaN,"{'facebook': None, 'instagram': None, 'twitter...","{'name': None, 'photoUrl': None, 'startDate': ...","[{'label': 'Product strategy', 'requirementSev...",NaN,NaN
13,5ce3fd8be2fd03a3,"{'page': 1, 'index': 9}",Technical Product Manager,[],"<div><p>Our client, a leading innovator in aut...",https://d2q79iu7y748jz.cloudfront.net/s/_squar...,"Our client, a leading innovator in autonomous ...",Manpower,https://www.indeed.com/cmp/Manpower,https://d2q79iu7y748jz.cloudfront.net/s/_heade...,...,"[Milwaukee, WI]","10,000+",more than $10B (USD),Every day tens of thousands of people go to wo...,{'year': 1948},{'facebook': 'https://www.facebook.com/Manpowe...,"{'name': 'Jonas Prising', 'photoUrl': 'https:/...",[],"Manpower, the global leader in contingent and ...",NaN
14,d6ed2d889fa6d7d5,"{'page': 1, 'index': 14}",Membership Platform Engineer (WordPress & Bill...,[Full-time],<p><b>Overview</b><br/>We are seeking an exper...,NaN,*Overview*\nWe are seeking an experienced back...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,{},{},"[{'label': 'Databases', 'requirementSeverity':...",NaN,NaN